apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy
spec:
  nodeSelector:
    matchLabels:
      bgp_enabled: "true"
  virtualRouters:
  - localASN: 64512
    exportPodCIDR: false
    neighbors:
    - peerAddress: '172.50.0.1/32'
      peerASN: 64513
    serviceSelector:
      matchExpressions:
      - {key: somekey, operator: NotIn, values: ['never-used-value']}