kubeProxyReplacement: "strict"
k8sServiceHost: "172.50.0.2"
k8sServicePort: "6443"
hostServices:
  enabled: false
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
image:
  pullPolicy: "IfNotPresent"
ipam:
  mode: "kubernetes"
k8s-require-ipv4-pod-cidr: true
tunnel: "vxlan"
cluster:
  name: "cilium-cluster"
operator:
  replicas: 1
ipv6:
  enabled: false
ipv4:
  enabled: true
# ---
bgpControlPlane:
  enabled: true
ingressController:
  default: false
  enabled: false
gatewayAPI:
  enabled: true
# ---
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
  tls:
    auto:
      enabled: true
      method: "helm"
      certValidityDuration: "1095"