apiVersion: v1
kind: Service
metadata:
  name: hubble-ipv6
  namespace: kube-system
  labels:
    bgp_enabled: "true"
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
  selector:
    k8s-app: hubble-ui
  sessionAffinity: None
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: shared-gw-ipv6
  namespace: kube-system
spec:
  gatewayClassName: cilium
  listeners:
  - name: shared-http-ipv6
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            shared-gw: "true"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hubble-ipv6-gw
  namespace: kube-system
spec:
  parentRefs:
  - name: shared-gw-ipv6
    namespace: kube-system
  hostnames:
  - hubble.example.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - kind: Service
      name: hubble-ipv6
      port: 80